<?php

use App\Models\Property\TypeOption;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TypeOptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement("SET foreign_key_checks=0");
        DB::table('type_options')->truncate();
        DB::statement("SET foreign_key_checks=1");

        $now = Carbon::now();
        $options=[
            ['type_spec_id' => '1',
                'name' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '1',
                'name' => '2',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '1',
                'name' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '1',
                'name' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '1',
                'name' => '5',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '2',
                'name' => '1-10',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '2',
                'name' => '10-20',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '2',
                'name' => '20-30',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '2',
                'name' => '30-40',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '2',
                'name' => '40-50',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '2',
                'name' => '50-60',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '2',
                'name' => '60-70',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '2',
                'name' => '70-80',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '2',
                'name' => '80-90',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '2',
                'name' => '90-100',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '3',
                'name' => 'شمالي',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '3',
                'name' => 'جنوبي',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '3',
                'name' => 'شرقي',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '3',
                'name' => 'غربي',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '4',
                'name' => 'جبل',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '4',
                'name' => 'حديقة',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '4',
                'name' => 'شارع',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '4',
                'name' => 'أرض',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '5',
                'name' => 'نعم',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '5',
                'name' => 'لا',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '6',
                'name' => 'مسبح',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '6',
                'name' => 'الديكور',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '6',
                'name' => 'الشرفة',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '6',
                'name' => 'التجهيزات',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '7',
                'name' => 'نعم',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '7',
                'name' => 'لا',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '8',
                'name' => 'نعم',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '8',
                'name' => 'لا',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '9',
                'name' => 'سيئة',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '9',
                'name' => 'جيدة',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '9',
                'name' => 'ممتازة',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '10',
                'name' => 'سيئة',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '10',
                'name' => 'جيدة',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '10',
                'name' => 'ممتازة',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '11',
                'name' => 'نعم',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '11',
                'name' => 'لا',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '12',
                'name' => 'نعم',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '12',
                'name' => 'لا',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '13',
                'name' => 'نعم',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '13',
                'name' => 'لا',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '14',
                'name' => 'نعم',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '14',
                'name' => 'لا',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '15',
                'name' => 'نعم',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '15',
                'name' => 'لا',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '16',
                'name' => 'نعم',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_spec_id' => '16',
                'name' => 'لا',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
        foreach ($options as $option)
        DB::table('type_options')->insert($option);

    }
}
